apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-name
  namespace: { { .Release.Namespace } }
  labels:
    app: app-name
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-name
    spec:
      containers:
        - name: app-name
          image: { { .Values.image } }
          imagePullPolicy: IfNotPresent
          resources: { { toYaml .Values.resources | indent 10 } }
          env:
            - name: ENV1
              value: { { .Values.envprop.name | quote } }
          ports:
            - name: api
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /*
              port: api
          readinessProbe:
            httpGet:
              path: /app/*
              port: api
            initialDelaySeconds: 5
            timeoutSeconds: 1
