apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-name
  namespace: { { .Release.Namespace } }
  labels:
    app: app-name
    chart: "{{.Chart.name}}-{{.Chart.Version}}"
spec:
  rules:
    - host: app-{{ .Release.Namespace }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: app-name
              servicePort: 9092
