apiVersion: v1
kind: Service
metadata:
  name: app-name
  namespace: { { .Release.Namespace } }
  labels:
    app: app-name
    chart: "{{ .Chart.Name}}-{{ .Chart.Version}}"
spec:
  type: ClusterIP
  ports:
    - name: root
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: app-name
